# air.toml

root = "."
tmp_dir = "tmp"
build_cmd = "go build -o ./tmp/main"
run_cmd = "./tmp/main"
include_ext = ["go", "html", "tmpl", "css", "js"]
exclude_dir = ["tmp", "vendor"]

[build]
  binary_name = "main"
  compile = true
  exclude_dir = ["frontend"]

[log]
  log_level = "debug"